!INTERFILE  :=
!imaging modality := PET
name of data file := scatter_low_res.s
originating system := BPET_Prototype_Leipzig
!version of keys := STIR4.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
patient orientation := head_in
patient rotation := supine
imagedata byte order := LITTLEENDIAN
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {None}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 1
matrix axis label [3] := view
!matrix size [3] := 24
matrix axis label [2] := axial coordinate
!matrix size [2] := {6}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 30
minimum ring difference per segment := {0}
maximum ring difference per segment := {0}
Scanner parameters:= 
Scanner type := BPET_Prototype_Leipzig
Number of rings                          := 6
Number of detectors per ring             := 48
Inner ring diameter (cm)                 := 25.4
Average depth of interaction (cm)        := 0.02
Distance between rings (cm)              := 2.1
Default bin size (cm)                    := 0.84
View offset (degrees)                    := 0
Maximum number of non-arc-corrected bins := 30
Default number of arc-corrected bins     := 30
Energy resolution := 17
Reference energy (in keV) := 511
Number of blocks per bucket in transaxial direction         := 1
Number of blocks per bucket in axial direction              := 1
Number of crystals per block in axial direction             := 6
Number of crystals per block in transaxial direction        := 6
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 1
Number of crystals per singles unit in transaxial direction := 1
Scanner geometry (BlocksOnCylindrical/Cylindrical/Generic)  := BlocksOnCylindrical
Scanner orientation (X or Y)                                := Y
end scanner parameters:=
effective central bin size (cm) := 0.84
number of time frames := 1
image duration (sec)[1] := 1e+09
image relative start time (sec)[1] := 0
number of energy windows := 1
energy window lower level[1] := 425
energy window upper level[1] := 650
start vertical bed position (mm) := 0
start horizontal bed position (mm) := 0
!END OF INTERFILE :=
